version: '3.8'
services:
  app:
    container_name: demo-spacy-ca-streamlit
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - LANG=ca
    ports:
      - '8081:8081'
